services:
  backend:
    image: gmeet-bot-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: int-meet-recorder
    privileged: true
    shm_size: "2gb"
    restart: unless-stopped
    ports:
      - "4000:8000"
      - "4014:6080"
    env_file:
      - ./.env
    environment:
      - DISPLAY=:99
      - PULSE_SERVER=unix:/var/run/pulse/native
      - PULSE_SINK=VirtualMic
      - PULSE_SOURCE=VirtualMicSource
    healthcheck:
      test: ["CMD-SHELL", "curl --connect-timeout 3 --fail http://localhost:8000/redoc || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./recordings:/app/recordings
      - ./chrome-profile:/tmp/chrome-profile
      - ./chrome-profile-backup:/tmp/chrome-profile-backup
